[files]
ignore-files = true
ignore-hidden = true
extend-exclude = [
    # not our typos
    "license.html",
    "tansu-sans-io/message",
]

[default]

[default.extend-words]
ser = "ser"
flate = "flate"
