apiVersion: v1
kind: Service
metadata:
  name: {{ include "tansu.fullname" . }}
  labels:
    {{- include "tansu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.kafkaPort }}
      targetPort: kafka
      protocol: TCP
      name: kafka
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tansu.selectorLabels" . | nindent 4 }}
