{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tansu.serviceAccountName" . }}
  labels:
    {{- include "tansu.labels" . | nindent 4 }}
{{- end }}
